#!/usr/bin/env python3
"""Prepare and verify the shared Octoscript-Makepad runtime source set."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess

HERE = Path(__file__).resolve().parents[1]
GENERATED = "# Generated by Octoscript-Makepad tools/runtime.py.\n"
MAKEPAD_URL = "https://github.com/OctoSense-org/makepad.git"
OCTOSCRIPT_URL = "https://github.com/OctoSense-org/Octoscript.git"
RUNTIME_URL = "https://github.com/OctoSense-org/Octoscript-Makepad.git"


def git(path, *args, check=True):
    return subprocess.run(["git", "-C", str(path), *args], check=check,
                          capture_output=True, text=True)


def manifest():
    value = json.loads((HERE / "runtime.json").read_text())
    expected = {"makepad": MAKEPAD_URL, "octoscript": OCTOSCRIPT_URL}
    if value.get("schema_version") != 1 or set(value.get("repositories", {})) != set(expected):
        raise ValueError("Unsupported Octoscript-Makepad runtime manifest")
    for name, url in expected.items():
        spec = value["repositories"][name]
        if spec.get("url") != url or not re.fullmatch(r"[0-9a-f]{40}", spec.get("revision", "")):
            raise ValueError(f"Invalid runtime source: {name}")
    cargo = (HERE / "Cargo.toml").read_text()
    for package, source in (("makepad-widgets", "makepad"), ("makepad-script", "makepad"),
                            ("octoscript-ui-l0", "octoscript")):
        declaration = re.search(r"^" + re.escape(package) + r"\s*=\s*\{([^\n]+)\}", cargo, re.M)
        revision = re.search(r'rev\s*=\s*"([0-9a-f]{40})"', declaration[1]) if declaration else None
        if not revision or revision[1] != value["repositories"][source]["revision"]:
            raise ValueError(f"Cargo.toml and runtime.json disagree about {package}")
    return value


def checkout_status(path):
    if not path.exists():
        return None
    if not (path / ".git").exists():
        if any(path.iterdir()):
            raise RuntimeError(f"{path} is not an empty directory or Git checkout")
        return None
    top = Path(git(path, "rev-parse", "--show-toplevel").stdout.strip()).resolve()
    if top != path.resolve():
        raise RuntimeError(f"{path} belongs to another checkout: {top}")
    return {"revision": git(path, "rev-parse", "HEAD").stdout.strip(),
            "dirty": bool(git(path, "status", "--porcelain", "--untracked-files=normal").stdout)}


def cargo_config(root):
    """Source overrides for generated WASM hosts; only reachable Git edges.

    Cargo cannot reliably reuse a locked graph with unused path patches.
    Checked-in workspaces declare their own minimal sibling overrides.
    """
    root = root.resolve()
    groups = {
        MAKEPAD_URL: {
            "makepad-widgets": root / "makepad/widgets",
            "makepad-script": root / "makepad/platform/script",
        },
        OCTOSCRIPT_URL: {
            "octoscript-ui-l0": root / "octoscript/crates/octoscript-ui-l0",
        },
        RUNTIME_URL: {
            name: root / "octoscript-makepad/crates" / name
            for name in ("octoscript-node",)
        },
    }
    text = GENERATED
    for url, crates in groups.items():
        text += f"\n[patch.{json.dumps(url)}]\n"
        for name, path in crates.items():
            text += f"{name} = {{ path = {json.dumps(str(path))} }}\n"
    return text


def prepare(root, *, update=False, cache=None):
    root = Path(root).resolve()
    if HERE != root / "octoscript-makepad":
        raise RuntimeError("Run the runtime tool from ROOT/octoscript-makepad")
    wrapper_state = checkout_status(HERE)
    if not wrapper_state or wrapper_state["dirty"]:
        raise RuntimeError("Preserving uncommitted Octoscript-Makepad changes")
    specs = manifest()["repositories"]
    # Preflight the whole source set before changing any checkout.
    states = {name: checkout_status(root / name) for name in specs}
    for name, state in states.items():
        if state and state["dirty"]:
            raise RuntimeError(f"{root / name} has local changes; preserve them before preparing the runtime")
        if state and state["revision"] != specs[name]["revision"] and not update:
            raise RuntimeError(f"{root / name} has another revision; use --update for a clean checkout")
    for name, spec in specs.items():
        path = root / name
        if states[name] and states[name]["revision"] == spec["revision"]:
            continue
        if states[name] is None:
            path.mkdir(parents=True, exist_ok=True)
            git(path, "init", "--quiet")
            git(path, "remote", "add", "origin", spec["url"])
        if git(path, "cat-file", "-e", spec["revision"] + "^{commit}", check=False).returncode:
            cached = Path(cache) / name if cache else None
            source = str(cached) if cached and (cached / ".git").exists() and not git(
                cached, "cat-file", "-e", spec["revision"] + "^{commit}", check=False).returncode else "origin"
            git(path, "fetch", "--quiet", "--no-tags", "--depth=1", source, spec["revision"])
        git(path, "checkout", "--quiet", "--detach", spec["revision"])
    receipt = verify(root)
    (root / ".octoscript-runtime.json").write_text(json.dumps(receipt, indent=2) + "\n")
    return receipt


def verify(root):
    root = Path(root).resolve()
    if HERE != root / "octoscript-makepad":
        raise RuntimeError("Runtime must be ROOT/octoscript-makepad")
    runtime_state = checkout_status(HERE)
    if not runtime_state or runtime_state["dirty"]:
        raise RuntimeError("Commit the Octoscript-Makepad runtime before verifying its release")
    sources = {}
    for name, spec in manifest()["repositories"].items():
        state = checkout_status(root / name)
        if not state or state["revision"] != spec["revision"] or state["dirty"]:
            raise RuntimeError(f"{root / name} differs from the unified runtime source lock")
        sources[name] = {"url": spec["url"], "revision": state["revision"]}
    return {"schema_version": 1, "runtime": {"url": RUNTIME_URL,
            "revision": git(HERE, "rev-parse", "HEAD").stdout.strip()},
            "repositories": sources,
            "manifest_sha256": hashlib.sha256((HERE / "runtime.json").read_bytes()).hexdigest()}


def verify_cargo(root, cargo_manifest):
    verify(root)
    metadata = json.loads(subprocess.check_output([
        "cargo", "metadata", "--locked", "--format-version", "1", "--manifest-path", str(cargo_manifest)
    ], cwd=Path(cargo_manifest).resolve().parent, text=True))
    critical = {"makepad-script", "makepad-platform", "makepad-draw", "makepad-widgets", "makepad-live-id"}
    seen = {}
    for package in metadata["packages"]:
        name = package["name"]
        if name not in critical:
            continue
        source = Path(package["manifest_path"]).resolve()
        if not source.is_relative_to(Path(root).resolve() / "makepad") or name in seen:
            raise RuntimeError(f"Multiple or foreign Makepad sources in Cargo graph: {name} ({source})")
        seen[name] = str(source)
    if not seen:
        raise RuntimeError("Cargo graph has no Makepad runtime")
    return seen


def verify_consumer(root, consumer):
    """Reject application manifests that introduce another framework revision."""
    root, consumer = Path(root).resolve(), Path(consumer).resolve()
    receipt = verify(root)
    expected = {spec["url"]: spec["revision"] for spec in receipt["repositories"].values()}
    expected[RUNTIME_URL] = receipt["runtime"]["revision"]
    lock = json.loads((consumer / "native-runtime.lock.json").read_text())
    if lock != {"schema_version": 1, **receipt["runtime"]}:
        raise RuntimeError(f"{consumer} selects another Octoscript-Makepad release")
    checked = []
    for directory, subdirs, filenames in os.walk(consumer):
        subdirs[:] = [name for name in subdirs if name not in {
            ".git", "target", "vendor", "octos", "node_modules", ".venv", "private", "runtime", "pipeline-output"
        }]
        if "Cargo.toml" not in filenames:
            continue
        path = Path(directory) / "Cargo.toml"
        for declaration in path.read_text().splitlines():
            if declaration.lstrip().startswith("#"):
                continue
            url = re.search(r'git\s*=\s*"([^"]+)"', declaration)
            if not url or url[1] not in expected:
                continue
            rev = re.search(r'rev\s*=\s*"([0-9a-f]{40})"', declaration)
            if not rev or rev[1] != expected[url[1]]:
                raise RuntimeError(f"{path}: dependency differs from Octoscript-Makepad/runtime.json: {declaration.strip()}")
        checked.append(str(path.relative_to(consumer)))
    return checked


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("prepare", "verify"))
    parser.add_argument("--root", type=Path, default=HERE.parent)
    parser.add_argument("--cache", type=Path)
    parser.add_argument("--update", action="store_true", help="Move clean dependency checkouts to the locked commits")
    parser.add_argument("--cargo-manifest", type=Path, help="Also reject duplicate/foreign Makepad crates in a Cargo graph")
    parser.add_argument("--consumer", type=Path, help="Check an application's runtime lock and Cargo pins")
    args = parser.parse_args()
    result = prepare(args.root, update=args.update, cache=args.cache) if args.command == "prepare" else verify(args.root)
    if args.cargo_manifest:
        result["cargo_sources"] = verify_cargo(args.root, args.cargo_manifest)
    if args.consumer:
        result["consumer_manifests"] = verify_consumer(args.root, args.consumer)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
